name: pruebas_pruebas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  provider: ^6.1.2
  google_mlkit_text_recognition: ^0.13.0
  dio: ^5.4.3+1
  xml: ^6.5.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  
flutter_native_splash:
  background_image: "assets/background.jpg"


flutter:
  uses-material-design: true
